week3/nrgweb/urls.py
'''
Created on 24 sep. 2013

@author: johan
'''

from django.conf.urls import patterns, url
import nrgweb.views
import nrgweb.google
import nrgweb.facebook

urlpatterns = patterns('',
    url(r'^$', nrgweb.views.index, name='index'),
    url(r'^login', nrgweb.views.login, name='login'),
    url(r'^logout', nrgweb.views.logout, name='logout'),
    url(r'^report', nrgweb.views.report, name='report'),
    url(r'^input', nrgweb.views.invoer, name='input'),
    url(r'^device$', nrgweb.views.invoerApparaat, name='device'),
    url(r'^measurements(/(?P<measurement_date>\d{4}-\d{2}-\d{2}))?', nrgweb.views.measurements, name='measurements'),
    url(r'^registered', nrgweb.views.registered, name='registered'),
    url(r'^register', nrgweb.views.register, name='register'),
    url(r'^avg/device/(?P<device_id>\d+)/?(?P<postcode>\d+)?', nrgweb.views.avg_per_device, name='avg_dev'),
    url(r'^avg/category/(?P<category>[a-zA-Z]+)/?(?P<postcode>\d+)?', nrgweb.views.avg_per_category, name='avg_cat'),
    url(r'^device/measurements/(?P<device_id>\d+)(/(?P<measurement_date>\d{4}-\d{2}-\d{2}))?', nrgweb.views.get_device_measurements, name='dev_get'),
    url(r'^googleauth', nrgweb.google.google_auth, name='google_auth'),
    url(r'^googleregister', nrgweb.google.google_register, name='google_register'),
    url(r'^facebookauth', nrgweb.facebook.facebook_auth, name='facebook_auth'),
    url(r'^facebookregister', nrgweb.facebook.facebook_register, name='facebook_register'),
)

week3/thema41wo3/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'thema41wo3.views.home', name='home'),
    # url(r'^thema41wo3/', include('thema41wo3.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^nrgweb/', include('nrgweb.urls', namespace = 'nrgweb')),
)

week3/nrgweb/models.py
'''
Created on 24 sep. 2013

@author: johan
'''

from django.db import models
import re

class Huishouden(models.Model):
    huishouden_id = models.AutoField(primary_key=True)
    straat = models.CharField(max_length=40)
    huisnummer = models.IntegerField()
    huisnummer_toevoeging = models.CharField(max_length=5, null=True)
    woonplaats = models.CharField(max_length=40)
    postcode = models.CharField(max_length=6)
    aantal_personen = models.IntegerField()
    email = models.CharField(max_length=40)
    telefoonnummer = models.CharField(max_length=10)
    password = models.CharField(max_length=40)

    def __unicode__(self):
        return self.huishouden_id

    
class ApparaatCategorie(models.Model):
    def __unicode__(self):
        return self.categorie
    
    categorie = models.CharField(max_length=20, primary_key=True)
    
class Apparaat(models.Model):
    apparaat_id = models.AutoField(primary_key=True)
    categorie = models.ForeignKey(ApparaatCategorie)
    merk = models.CharField(max_length=40)
    typenummer = models.CharField(max_length=40)

    def __unicode__(self):
        return "{0} - {1} ({2})".format(self.merk, self.typenummer, self.categorie)

class HuishoudenApparaat(models.Model):
    def __unicode__(self):
        return self.apparaat.typenummer
        
    huishouden = models.ForeignKey(Huishouden)
    apparaat = models.ForeignKey(Apparaat)
    
class MetingTijden(models.Model):
    tijd = models.TimeField(primary_key=True)
    
class Meting(models.Model):
    meting_id = models.AutoField(primary_key=True)
    apparaat = models.ForeignKey(HuishoudenApparaat)
    datum = models.DateField()
    tijd = models.TimeField()
    waarde = models.DecimalField(decimal_places=2, max_digits=4)
    huishouden = models.ForeignKey(Huishouden)

class GoogleAuth(models.Model):
    user_id = models.CharField(primary_key=True, max_length=30)
    token_expires = models.BigIntegerField()
    time_issued = models.BigIntegerField()
    email = models.CharField(max_length=40)
    huishouden = models.ForeignKey(Huishouden, blank=True, null=True)

class FacebookAuth(models.Model):
    user_id = models.CharField(primary_key=True, max_length=30)
    token_expires = models.BigIntegerField()
    huishouden = models.ForeignKey(Huishouden, blank=True, null=True)

week3/nrgweb/forms.py
'''
Created on 25 sep. 2013

@author: johan
'''

from django import forms
from nrgweb.models import MetingTijden, Meting, Huishouden, Apparaat, HuishoudenApparaat
from datetime import date
from nrgweb.util import get_time_values

class RegistrationForm(forms.ModelForm):
    password = forms.PasswordInput()
    huisnummer_toevoeging = forms.CharField(required=False)
    class Meta:
        model = Huishouden
        fields = [ 'straat', 'huisnummer', 'huisnummer_toevoeging', 'woonplaats', 'postcode',
                   'aantal_personen', 'email', 'telefoonnummer', 'password' ]

class LoginForm(forms.Form):
    email = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

class NrgInputForm(forms.ModelForm):
    datum = forms.CharField(initial=date.today().isoformat())
    tijd = forms.ChoiceField(choices=get_time_values(MetingTijden.objects.values_list()))

    class Meta:
        model = Meting
        fields = ['datum', 'tijd', 'waarde', 'apparaat' ]
        
class DeviceInputForm(forms.ModelForm):
    merk = forms.CharField()
    typenummer = forms.CharField()
    
    class Meta:
        model = Apparaat
        fields = [ 'merk', 'typenummer', 'categorie' ]

class DeviceLinkForm(forms.ModelForm):
    class Meta:
        model = HuishoudenApparaat
        fields = ['apparaat']

week3/nrgweb/views.py
'''
Created on 24 sep. 2013

@author: johan & vincent
'''

from django.shortcuts import render
from nrgweb.forms import RegistrationForm, LoginForm, NrgInputForm, DeviceInputForm, DeviceLinkForm
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from nrgweb.models import Huishouden, HuishoudenApparaat, Apparaat, MetingTijden, Meting
from nrgweb.util import *
import json
import nrgweb.google
import nrgweb.facebook

def index(request):
    """Main view"""
    return render(request, 'index.html', {'session': request.session})

def register(request):
    """"User registration view"""

    # Check if user registration needs to be handled elsewhere.
    if "auth_provider" in request.session:
        if request.session["auth_provider"] == "google":
            return HttpResponseRedirect(reverse('nrgweb:google_register'))
        elif request.session["auth_provider"] == "facebook":
            pass

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('nrgweb:registered'))
    else:
        form = RegistrationForm()
    return render(request, 'register.html', {'form': form})

def login(request):
    """Login view"""
    # Check if the user has been logged in already.
    if is_logged_in(request):
        return HttpResponseRedirect(reverse('nrgweb:input'))

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            # Authenticate the user.
            huishouden = Huishouden.objects.get(email=request.POST['email'])
            if huishouden.password == request.POST['password']:
                request.session['logged_in'] = True
                request.session['huishouden'] = huishouden
                # Check if redirection after logging in is requested by some view.
                if 'redirect_after_login' in request.session:
                    redirect_to = request.session['redirect_after_login']
                    del request.session['redirect_after_login']
                else:
                    # Default redirection destination
                    redirect_to = 'nrgweb:measurements'
                return HttpResponseRedirect(reverse(redirect_to))
    else:
        form = LoginForm()
        template_data = {'form': form, 'session': request.session}
        #template_data['google_auth_url'] = google.get_authorization_url()
        #template_data['facebook_auth_url'] = facebook.get_authorization_url()
        return render(request, 'login.html', template_data)

def logout(request):
    # Delete the 'user logged in' key if it exists.
    if 'logged_in' in request.session:
        request.session.flush()
    return HttpResponseRedirect(reverse('nrgweb:index'))

def report(request):
    """Reporting view"""
    if not is_logged_in(request):
        request.session['redirect_after_login'] = 'nrgweb:report'
        return HttpResponseRedirect(reverse('nrgweb:login'))
    
    # Initialize the template data.
    template_data = {'session': request.session}
    # Get the huishouden object.
    huishouden = Huishouden.objects.get(huishouden_id=request.session['huishouden'].huishouden_id)

    # Generate the device list.    
    dev_info = get_device_list(huishouden.huishouden_id)
    template_data['devices'] = dev_info[0]
    if len(template_data['devices']) > 0:
        template_data['deviceList'] = dev_info[1]
        print(dev_info[1])

    return render(request, 'report.html', template_data)

def invoer(request):
    """Measurement input view"""
    if not is_logged_in(request):
        request.session['redirect_after_login'] = 'nrgweb:input'
        return HttpResponseRedirect(reverse('nrgweb:login'))

    # Initialize the template data.
    template_data = {'session': request.session}
    # Get the huishouden object.
    huishouden = Huishouden.objects.get(huishouden_id=request.session['huishouden'].huishouden_id)

    # Generate the device list.
    dev_info = get_device_list(huishouden.huishouden_id)
    if dev_info is None:
        request.session["statusmsg"] = "Er is nog geen apparaat ingevoerd. Voert u aub eerst een apparaat in"
        return HttpResponseRedirect(reverse('nrgweb:device'))

    # Get the device list.
    template_data['devices'] = dev_info[0]
    if len(template_data['devices']) > 0:
        template_data['deviceList'] = dev_info[1]

    # Check if data was posted.
    if request.method == 'POST':
        nrgForm = NrgInputForm(request.POST)
        if nrgForm.is_valid():
            # Get the "meting" object from the form.
            meting = nrgForm.save(commit=False)
            # Set the huishouden (mandatory foreign key).
            meting.huishouden = huishouden
            # Save it.
            meting.save()
            # Redirect to the measurements page
            return HttpResponseRedirect(reverse('nrgweb:measurements'))
    else:
        nrgForm = NrgInputForm()
        nrgForm.fields['apparaat'].queryset = HuishoudenApparaat.objects.filter(huishouden_id=huishouden.huishouden_id)

    template_data['nrgForm'] = nrgForm
    return render(request, 'input.html', template_data)

def invoerApparaat(request):
    """View handling the addition of devices"""
    if not is_logged_in(request):
        request.session['redirect_after_login'] = 'nrgweb:device'
        return HttpResponseRedirect(reverse('nrgweb:login'))

    if 'statusmsg' in request.session:
        statusmsg = request.session['statusmsg']
        del request.session['statusmsg']
    else:
        statusmsg = None

    if request.method == 'POST':
        _huishouden_id = request.session['huishouden'].huishouden_id
        if not 'apparaat' in request.POST:
            form = DeviceInputForm(request.POST)
            if request.POST.get('deviceId') in ['none']:   # Add a device since there is no ID
                if form.is_valid():
                    newDevice = form.save() # get the device object just added to Apparaat
                    newHuishoudenApparaat = HuishoudenApparaat(huishouden_id = _huishouden_id, apparaat_id = newDevice.pk)
                    newHuishoudenApparaat.save()
            else:
               device = HuishoudenApparaat.objects.filter(pk = request.POST.get('deviceId'))
               # remove apparaat record
               Apparaat.objects.filter(pk = device[0].apparaat_id).delete()
               # remove Huishouden apparaat record
               device.delete()
        else:
            form = DeviceLinkForm(request.POST)
            if form.is_valid():
                newLink = form.save(commit=False)
                newLink.huishouden = Huishouden.objects.get(huishouden_id=_huishouden_id)
                newLink.save()

        return HttpResponseRedirect(reverse('nrgweb:device'))
    else:
        deviceForm = DeviceInputForm()
        devices = HuishoudenApparaat.objects.filter(huishouden = request.session['huishouden'].huishouden_id).values_list()
        linkForm = DeviceLinkForm()
        deviceList = []
        for device in devices:
            items = list(Apparaat.objects.filter(apparaat_id = device[2]).values()) # get columnvalues for the device
            items.append (device[0]) # add unique device id to list of columnvalues
            deviceList.append(items) # add device items to list
        return render(request, 'inputDevice.html', {'session' : request.session,
                                                    'deviceForm': deviceForm,
                                                    'deviceList' : deviceList,
                                                    'linkForm': linkForm,
                                                    'statusmsg': statusmsg})

def registered(request):
    """View rendered when a user has registered"""
    return render(request, 'registered.html', {'session': request.session})

def is_logged_in(request):
    """Determine if the user is logged in """
    return 'logged_in' in request.session and request.session['logged_in']

def measurements(request, measurement_date=None):
    # Redirect if not logged in.
    if not is_logged_in(request):
        request.session['redirect_after_login'] = 'nrgweb:measurements'
        return HttpResponseRedirect(reverse('nrgweb:login'))

    # Set the measurement date to today if no date is given.
    if measurement_date is None:
        from datetime import date
        measurement_date = date.today().isoformat()

    # Get the measurement dates.
    dates = get_measurements_dates(request.session['huishouden'].huishouden_id)

    # Initialize template data.
    template_data = {'session': request.session, 'dates': dates, 'measurement_date': measurement_date}

    # Find all measurements for the given date.
    if len(dates) > 0:
        from nrgweb.util import get_measurement_table
        measurements = get_measurement_table(request.session['huishouden'].huishouden_id,
                                                              measurement_date)
        if measurements is not None:
            template_data['measurements'] = measurements

    return render(request, 'measurements.html', template_data)


def avg_per_device(request, device_id, postcode = None):
    """Average per device view"""
    return HttpResponse(json.dumps(get_averages_for_device(device_id, postcode)), content_type="application/json")

def avg_per_category(request, category, postcode = None):
    """Average per category view"""
    return HttpResponse(json.dumps(get_averages_for_category(category, postcode)), content_type="application/json")

def get_device_measurements(request, device_id, measurement_date = None):
    """Get a JSON list of device measurements"""
    return HttpResponse(json.dumps(get_measurements_for_device(device_id, measurement_date)), content_type="application/json")

week3/nrgweb/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}NRGWeb: Al uw energie onder controle!{% endblock %}</title>
	<link rel="stylesheet/less" type="text/css" href="{% static "css/styles.less" %}" />
	<script src="{% static "js/less-1.4.1.js" %}" type="text/javascript"></script>
	<script src="{% static "js/jquery.js" %}" type="text/javascript"></script>
	<script src="{% static "js/raphael.js" %}" type="text/javascript"></script>
	<script src="{% static "js/g.raphael.js" %}" type="text/javascript"></script>
	<script src="{% static "js/g.line.js" %}" type="text/javascript"></script>
{% block headerinclude %}{% endblock %}
</head>
<body id="{% block bodyid %}{% endblock %}" >	
	
	<div class="left">		
	  	<nav>
	  		<ul class="navlist">
	  			 <li><a href="{% url 'nrgweb:index' %}" id="index">&nbsp;Start</a></li>
			     {% if session.logged_in %}
			     	<li><a href="{% url 'nrgweb:logout' %}" id="logout">&nbsp;Uitloggen</a></li>
				    <li><a href="{% url 'nrgweb:input' %}" id="input_nrg">&nbsp;NRG invoeren</a></li>
				    <li><a href="{% url 'nrgweb:device' %}" id="inputDevice">&nbsp;Apparaat invoeren</a></li>
				    <li><a href="{% url 'nrgweb:report' %}" id="report">&nbsp;Rapporteren</a></li>
				    <li><a href="{% url 'nrgweb:measurements' %}" id="measurements">&nbsp;Metingen</a></li>
			     {% else %}
			     <li><a href="login" id="login">&nbsp;Inloggen</a></li>
			     {% endif %}
	    		</ul>
	   	</nav>
 	</div>

  	<div id="ruler">
  		{% if session.logged_in %}Ingelogd als: {{ session.huishouden.email }}{% endif %}
  	</div>
	<div id="logo">
		<!-- Logo borrowed from http://www.freelanceoffset.com/html/copiers___printers.html and NRG a Ricoh company -->
		<img src="{% static "images/nrglogo.gif" %}" alt="NRG logo">
	</div>	
	<div id="content">
	{% block content %}
	{% endblock %}
	</div>
</body>
</html>

week3/nrgweb/templates/index.html
{% extends "base.html" %}
{% block bodyid %}index{% endblock %}
{% block title %}Rapporteer{% endblock %}
{% block content %}
<h1>Welkom bij NRGWeb</h1><br/>
NRGWeb is al sinds jaar en dag een begrip op het gebied van particuliere energieproductie. Op deze pagina kunt u de energieproductie van al uw apapratuur invoeren, beheren en bekijken. Tevens kunt u vergelijkingen maken met andere gebruikers en uw gehele omgeving.
<br/><br/>
Wacht dus niet langer en registreer vandaag nog! Het is gratis :-).
{% endblock %}

week3/nrgweb/templates/input.html
{% extends "base.html" %}
{% block bodyid %}input{% endblock %}
{% block title %}Invoeren{% endblock %}
{% block content %}
	<h1>Energie opwekking invoeren</h1>
{% if deviceList %}
	<fieldset class="registration">
		<legend>Ingevoerde apparaten</legend>
		<table>
			<tr>
				<th>Merk</th><th>Type</th><th>Categorie</th>
			</tr>
			{% for device in deviceList %}
				<tr>
					<td>		
					{{ device.0.merk }}
					</td>
					<td>		
					{{ device.0.typenummer }}
					</td>				
					<td>		
					{{ device.0.categorie_id }}
					</td>
				</tr>
			{% endfor %}
		</table>
	</fieldset>
	<br/>	
	<form id="nrginput" action="{% url 'nrgweb:input' %}" method="post">
		{% csrf_token %}
		<fieldset class="registration">
		   	<legend>Invoer meting</legend>
			<table>
				{% for field in nrgForm %}	
				<tr>
					<td>
						{{ field.label }}:
					</td>
					<td>
						{{ field }}
						</td>
					<td>{{ field.errors }}
					</td>
				</tr>
			{% endfor %}
			</table>
			<div class="registration_input" >	    
				<input type="submit" class="registration_textbox" value="Invoeren" />
			</div>	
		</fieldset>
	</form>
{% else %}
Er zijn nog geen apparaten ingevoerd. Voer <a href="{% url 'nrgweb:device' %}">hier</a> een nieuw apparaat in.
{% endif %}
{% endblock %}

week3/nrgweb/templates/inputDevice.html
{% extends "base.html" %}
{% block bodyid %}inputDevice{% endblock %}
{% block title %}Invoeren apparaat{% endblock %}
{% block content %}
<h1>Apparaten invoeren</h1>

{% if statusmsg %}
<h2>Status bericht</h2>
<p>{{ statusmsg }}</p>
{% endif %}

<fieldset class="registration">
    <legend>Ingevoerde apparaten</legend>
    <table>
        <tr>
            <th>Merk</th><th>Type</th><th>Categorie</th>
        </tr>
        {% for device in deviceList %}
        <tr>

        <form id="deleteDevice" action="{% url 'nrgweb:device' %}" method="post">
        {% csrf_token %}
            <td>
            {{ device.0.merk }}
            </td>
            <td>
            {{ device.0.typenummer }}
            </td>
            <td>
            {{ device.0.categorie_id }}
            </td>
            <td>
                <input type="submit" class="registration_textbox" value="Verwijderen" />
                <input type="hidden" name="deviceId" value="{{ device.1 }}" />
            </td>
        </form>
        </tr>

        {% endfor %}

        <form id="inputDevice" action="{% url 'nrgweb:device' %}" method="post">
        {% csrf_token %}
        <tr>
            {% for field in deviceForm %}
            <td>
                {{ field }}
            </td>
            {% endfor %}
            <td>
                <input type="submit" class="registration_textbox" value="Toevoegen&nbsp;&nbsp;" />
                <input type="hidden" name="deviceId" value="none" />
            </td>
            <td>
            {{ field.errors }}
            {{ field.non_field_errors }}
            </td>
            </tr>

    </table>
</fieldset>
</form>

<br/>

<form id="linkDevice" action="{% url 'nrgweb:device' %}" method="post">
{% csrf_token %}
<fieldset class="registration">
    <legend>Bestaand apparaat selecteren</legend>
    <table>
        {% for field in linkForm %}
        <tr>
            <td>
                {{ field.label }}:
            </td>
            <td>
                {{ field }}
                </td>
            <td>{{ field.errors }}
            </td>
        </tr>
    {% endfor %}
    </table>
    <input type="submit" value="Voeg apparaat toe">
</fieldset>
</form>
{% endblock %}

week3/nrgweb/templates/login.html
{% extends "base.html" %}
{% load staticfiles %}
{% block bodyid %}login{% endblock %}
{% block title %}Inloggen{% endblock %}
{% block content %}
<h1>Inloggen</h1><br/>
Om in te loggen kunt u hieronder uw inloggegevens invoeren. Hebt nog geen inloggegevens dan kunt u zich gratis <a href="{% url 'nrgweb:register' %}">registreren</a>.
<br/><br/>

<form action="{% url 'nrgweb:login' %}" method="post">
{% csrf_token %}
<fieldset class="registration">
     <legend>Login-gegevens</legend>
<table>
{% for field in form %}
	<tr>
		<td>
			{{ field.label_tag }}:
		</td>
		<td>
			{{ field }}
		</td>
		<td>{{ field.errors }}
	</tr>
{% endfor %}
</table>
<input type="submit" class="registration_textbox" value="Login" />
	
</fieldset>
</form>

<fieldset class="">
    <legend>Login met Facebook/Google</legend>
<a title="Inloggen met Google"
   href="{{ google_auth_url }}"
   style="background: #fff url({% static 'images/openid-logos.png' %}); background-position: -1px -1px"
   class="icon-google openid_large_btn"></a>
<a title="Inloggen met Facebook"
   href="{{ facebook_auth_url }}"
   style="background: #fff url({% static 'images/openid-logos.png' %}); background-position: -1px -456px"
   class="icon-facebook openid_large_btn"></a>
</fieldset>

{% endblock %}

week3/nrgweb/templates/measurements.html
{% extends "base.html" %}
{% block header_include %}
<script>

</script>
{% endblock %}
{% block bodyid %}measurements{% endblock %}
{% block title %}Metingen{% endblock %}
{% load keyvalue %}
{% block content %}
<h1>Overzicht van metingen</h1><br/>

{% if dates %}
<h2>Selecteer een datum</h2>
Datum:
<select name="datum" onchange="if (this.value != '-----------') window.location.href = '{% url 'nrgweb:measurements' %}/' + this.value;">
        <option value="{{ date }}">-----------</option>
    {% for date in dates %}
        <option value="{{ date }}">{{ date }}</option>
    {% endfor %}
</select>

{% if measurements %}
<h2>Metingen voor datum {{ measurement_date }}</h2>
<table class="measurement_table">
    <thead>
        <tr>
            <th colspan="2" valign="top">Apparaat</th>
            {% for time in measurements.times %}
            <th>{{ time.1 }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for device_id, device in measurements.devices.items %}
        <tr>
            <th rowspan="2">{{ device.name }}</th>
            <th>i (kW)</th>
                {% for time in measurements.times %}
                <td>{{ device.values|measurement_value:time.1 }}</td>
                {% endfor %}
        </tr>
        <tr>
            <th>sum(i) (kWh)</th>
                {% for time in measurements.times %}
                <td>{{ device.values|measurement_sum_value:time.1 }}</td>
                {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>Geen metingen gevonden voor datum {{ measurement_date }}.
Voer <a href="{% url 'nrgweb:input' %}">hier</a> een nieuwe meting in.
</p>
{% endif %}

{% else %}
Geen metingen gevonden. Voer <a href="{% url 'nrgweb:input' %}">hier</a> een nieuwe meting in.
{% endif %}
{% endblock %}

week3/nrgweb/templates/register.html
{% extends "base.html" %}
{% block title %}Registreren{% endblock %}
{% block content %}
<h1>Registreren</h1>

{% if session.auth_provider == 'google' or session.auth_provider == 'facebook' %}
<h2>Registratie voor {{ session.auth_provider }} account</h2>
<p>U heeft ingelogd met uw {{ session.auth_provider }} account.
Aangezien uw account niet verbonden is aan bestaande gegevens,
dient u deze alsnog in te vullen. Deze gegevens zijn vervolgens gekoppeld aan uw {{ session.auth_provider }} account.</p>
{% endif %}

{% if session.auth_provider == 'google' %}
<form action="{% url 'nrgweb:google_register' %}" method="post">
{% elif session.auth_provider == 'facebook' %}
<form action="{% url 'nrgweb:facebook_register' %}" method="post">
{% else %}
<form action="{% url 'nrgweb:register' %}" method="post">
{% endif %}
{% csrf_token %}
<fieldset class="registration">
     <legend>Gegevens huishouding</legend>
<table>
{% for field in form %}
	<tr>
		<td>
			{{ field.label_tag }}:
		</td>
		<td>
			{{ field }}
		</td>
		<td>{{ field.errors }}
	</tr>
{% endfor %}
</table>
		<div class="registration_input" >	    
	        <input type="submit" class="registration_textbox" value="Registreer!" />
		</div>
	
</fieldset>
</form>
{% endblock %}

week3/nrgweb/templates/registered.html
{% extends "base.html" %}
{% block bodyid %}input{% endblock %}
{% block title %}Registratie voltooid{% endblock %}
{% block content %}
<h1>Registratie voltooid!</h1><br/>
U kunt nu <a href="{% url 'nrgweb:login' %}">hier</a> inloggen.
{% endblock %}

week3/nrgweb/templates/report.html
{% extends "base.html" %}
{% block bodyid %}report{% endblock %}
{% block title %}Rapporteren{% endblock %}
{% load staticfiles %}
{% block headerinclude %}
<script type="text/javascript" src="{% static "js/graphing.js" %}"></script>
<script type="text/javascript">
function compareData() {
    var postcode = $('#postcode').val();
    var device_info = $('#device_info').val().split('/');
    var deviceId = device_info[0];
    var category = device_info[1];
    var check_type = $('input[name=avg_type]:checked', '#report_form').val();
    
 	// Get device data url
   	var url = "{% url 'nrgweb:dev_get' device_id=0 %}".replace(/0$/, deviceId);
    
    // Get avg data baseurl
    var base_url_avg;
    if (check_type == 'device')
	    base_url_avg = "{% url 'nrgweb:avg_dev' device_id=0 %}".replace(/0$/, deviceId);
	else
	    base_url_avg = "{% url 'nrgweb:avg_cat' category='Fiets' %}".replace(/Fiets$/, category);


   	// Should a postcode be added?
   	var url_avg;
  	if (typeof postcode == 'string' && postcode.length > 0)
    	url_avg = base_url_avg + "/" + postcode;
   	else
      	url_avg = base_url_avg;

    // Get the data.
    getData(url, url_avg); // Retrieve data and draw graph
}
</script>
{% endblock %}
{% block content %}
<h1>Rapportage energie opwekking</h1><br/>
<p>Selecteer een apparaatcategorie om te vergelijken en geef een postcodegebied in of geen postcode voor het gehele land.</p>
<form id="report_form">
    Apparaat:
    <select id="device_info">
    {% for device in deviceList %}
      <option value="{{ device.1 }}/{{ device.0.categorie_id }}">{{ device.0.merk }} {{ device.0.typenummer }} {{ device.0.categorie_id }}</option>
    {% endfor %}
    </select>

    <br/>
    Gemiddelde voor:
    <input id="avg_for_device" type="radio" name="avg_type" value="device" checked>
    <label for="avg_for_device">Apparaat van hetzelfde type</label>
    <input id="avg_for_category" type="radio" name="avg_type" value="category">
    <label for="avg_for_category">Apparaat in dezelfde categorie</label>

    <br/>
    Postcode:<input id="postcode" type="text" class="registration_textbox" value="9000" size="4" maxlength="4" />
    <input type="button" class="registration_textbox" value="Vergelijk!" onclick="compareData()"/>
</form>
<br/><br/>

<div id="holder"></div>
<p>
    Created with <a href="http://g.raphaeljs.com/">gRaphaël</a> JavaScript library.
</p>
{% endblock %}